import sys
from supabase import create_client, Client
from configs.settings import settings
from core.utils.logger import get_logger

# Import your newly created modules
from platforms.threads.client import ThreadsClient
from core.interaction_engine.inbound.sweeper import InboundSweeper
from core.interaction_engine.inbound.community_manager import CommunityManager

logger = get_logger("orbit.inbound.runner")

class InboundOrchestrator:
    def __init__(self):
        """
        Initializes the entire inbound pipeline, spinning up the Meta client,
        the timeline sweeper, the Gemini engine, and the database connection.
        """
        self.logger = logger
        self.logger.info("[ORCHESTRATOR] Initializing inbound interaction pipeline...")
        
        try:
            # Initialize core clients
            self.threads_client = ThreadsClient()
            self.supabase: Client = create_client(settings.SUPABASE_URL, settings.SUPABASE_KEY)
            
            # Initialize pipeline components
            self.sweeper = InboundSweeper(threads_client=self.threads_client)
            self.community_manager = CommunityManager()
            
        except Exception as e:
            self.logger.critical(f"[ORCHESTRATOR INIT CRITICAL] Pipeline initialization failed: {e}")
            sys.exit(1)

    def execute_pipeline(self):
        """
        Runs the complete cycle: Sweep -> Think -> Reply -> Remember.
        """
        # Step 1: Sweep the timeline for un-interacted comments
        unanswered_queue = self.sweeper.sweep_for_unanswered()
        
        if not unanswered_queue:
            self.logger.info("[ORCHESTRATOR] Zero actionable comments found in queue. Pipeline finishing cleanly.")
            return

        # Step 2: Pass the queue to Gemini for unified batch processing
        generated_replies = self.community_manager.generate_replies(unanswered_queue)
        
        if not generated_replies:
            self.logger.warning("[ORCHESTRATOR] No replies were successfully generated by the LLM layer. Aborting execution.")
            return

        # Step 3: Publish replies to Threads and commit state logs to Supabase
        self.logger.info(f"[ORCHESTRATOR] Ready to publish {len(generated_replies)} replies to the timeline...")
        
        success_count = 0
        
        for reply in generated_replies:
            post_id = reply["post_id"]
            comment_id = reply["comment_id"]
            username = reply["username"]
            reply_text = reply["reply_text"]

            self.logger.info(f"[ORCHESTRATOR] Publishing reply to @{username} on post {post_id}...")
            
            try:
                # 1. Post to Meta API using the dedicated method
                response = self.threads_client.publish_reply(
                    text=reply_text,
                    reply_to_id=comment_id
                )
                
                if response:
                    self.logger.info(f"[ORCHESTRATOR] Successfully posted reply to comment {comment_id}.")
                    
                    # 2. COMMIT STATE TO SUPABASE (The Shield Activates)
                    # This insert must happen immediately to secure transactional safety.
                    self.supabase.table("inbound_interactions").insert({
                        "post_id": post_id,
                        "comment_id": comment_id,
                        "username": username
                    }).execute()
                    
                    self.logger.debug(f"[ORCHESTRATOR] State locked in DB for comment {comment_id}.")
                    success_count += 1
                else:
                    self.logger.error(f"[ORCHESTRATOR ERROR] ThreadsClient returned an empty response for comment {comment_id}.")

            except Exception as e:
                self.logger.error(f"[ORCHESTRATOR CRITICAL LOOP ERROR] Failed to complete cycle for comment {comment_id}: {e}")
                # Continue processing the rest of the batch even if one item hits an API wall
                continue

        self.logger.info(f"[ORCHESTRATOR] Inbound cycle completed. Successfully executed {success_count}/{len(generated_replies)} interactions.")

if __name__ == "__main__":
    orchestrator = InboundOrchestrator()
    orchestrator.execute_pipeline()
